### ISSUE TITLE
fire render tutorials on nvidia

### ISSUE THREAD

**Issue by eythymis** [amdadvtech/FireRenderSDK#1]
1) i try to add an area light and a reflection shader in the scene and they did not work
2) when i put an environment light in the scene the program crash

i use a laptop with two GPUs
a) Intel HD Graphics 4000
b) NVIDIA GeForce GT 640M

**Comment by bstefanizzi** [comment]
If you install the intel OpenCL driver, it will work. For nvidia, you need a card supporting OpenCL 1.2 and we found several issues with their OpenCL driver that we are working on to workarounds them. You should have a new version soon.

**Comment by eythymis** [comment]
Thanks for the answer, this time the only thing that matters is to incorporate the FireRenter in our application, so i would like to tell me what amd graphics cards are fully compatible with FireRender

**Comment by bstefanizzi** [comment]
All GCN based cards (Radeon or FirePro W series and S series).
